name: Bug Report
description: Report a bug in ProxyBridge
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ProxyBridge Version
      description: What version of ProxyBridge are you running?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS and Version
      description: What operating system and version are you using?
      placeholder: e.g., Windows 11 23H2, macOS 14.2 Sonoma, Ubuntu 22.04
    validations:
      required: true

  - type: checkboxes
    id: documentation
    attributes:
      label: Documentation
      description: Have you read the documentation for your platform?
      options:
        - label: I have read the [Windows documentation](https://github.com/InterceptSuite/ProxyBridge/blob/master/Windows/README.md)
          required: false
        - label: I have read the [macOS documentation](https://github.com/InterceptSuite/ProxyBridge/blob/master/MacOS/README.md)
          required: false
        - label: I have read the [Linux documentation](https://github.com/InterceptSuite/ProxyBridge/blob/master/Linux/README.md)
          required: false

  - type: checkboxes
    id: code-review
    attributes:
      label: Code Review
      description: Have you reviewed the code?
      options:
        - label: I have gone through the code page
          required: false

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: |
        Please provide a clear and detailed description of the bug.

        **If applicable, please include:**
        - Screenshots or error messages
        - Steps to reproduce the issue
        - Expected behavior vs actual behavior
      placeholder: |
        Steps to reproduce:
        1. Go to '...'
        2. Click on '...'
        3. See error

        Expected behavior: ...
        Actual behavior: ...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (logs, configuration files, etc.)
      placeholder: Paste any relevant logs or additional information here
